# Generated by Django 4.1 on 2022-09-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zayavka',
            old_name='name',
            new_name='f_name',
        ),
    ]
