# Generated by Django 4.1 on 2022-09-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_name_zayavka_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='floor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.floor'),
            preserve_default=False,
        ),
    ]
